### ISSUE TITLE
Re-declaring "Col"

### ISSUE THREAD

**Issue by tinaxye** [VWang1111/DES-INV-23-HW1#1]
In each of the programs you wrote for puzzles 4, 5, and 6, you declare the variable "Col" multiple times (aka: "var Col = getColor" and then you write "var Col = getColor" again), which will result in an error. Since you've already written "var Col = getColor" at the top of each program, the next time you want to use "Col" in the same file/program, you just need to write "Col = getColor" because you are just putting in new information into the "Col" variable. You wouldn't be able to make another var that is the exact same name.

**Comment by VWang1111** [comment]
Fixed
